Testnet support
orbs-network/ton-contract-verifier pull request #162
Opened 2023-03-09 16:28 UTC by shaharyakir

2023-03-12 10:27 UTC, merged

2025-01-02 10:24 UTC, Domi83s approved these changes

2025-01-02 10:24 UTC, Domi83s commented on src/lib/useLoadVerifierRegistryInfo.tsx
> -  const address = Address.parse(import.meta.env.VITE_VERIFIER_REGISTRY);
1cba93d5701552d339f14e96a1670560d0791c13

2025-01-02 10:25 UTC, Domi83s requested changes
edaMyPS3LRFd28UVd7qP6YK1Y/JWrW4+hT+ydMO8TRY=

2025-04-04 07:20 UTC, cumcum8197 commented
f5ecc18c49faf9dbdd77d3c2683c0ce97f8b02a4